# Project Name
TARGET = i2cleadertest

# Sources
CPP_SOURCES = i2cleadertest.cpp ../../lib/daisy_dpt.cpp ../../lib/dev/DAC7554.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

